server:
  port: 8080
  servlet:
    context-path: /security-spring-security
#    session:
#      cookie:
#        http-only: true # 如果为true, 那么浏览器脚本将无法访问cookie
#        secure: true # 如果为true, 则cookie将仅通过HTTPS连接发送
#      timeout: 3600s # session超时时间，超时就消除了
spring:
  application:
    name: springboot-security
